# Generated by Django 4.2.5 on 2023-10-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_rename_linktophoto_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessphoto',
            name='dataSeen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
